import type { GalleryDeploymentConfig } from './deploymentConfig';
import type { ManagedGroupPlugin, ManagedGroupCommandContext, ManagedGroupRuntimeContext } from '@wabs/plugin-sdk/managed-group-plugin';
export { requireManagedGroupCommandRuntime as requireOfficialCommandRuntime } from '@wabs/plugin-sdk/managed-group-plugin';
export { requireScopeId, parseBoolean } from '@wabs/plugin-sdk/commands';
export type BotPlugin = ManagedGroupPlugin<GalleryDeploymentConfig>;
export type PluginCommandContext = ManagedGroupCommandContext<GalleryDeploymentConfig>;
export type PluginRuntimeContext = ManagedGroupRuntimeContext<GalleryDeploymentConfig>;
export type PluginExternalActionRegistrationContext = ManagedGroupRuntimeContext<GalleryDeploymentConfig>;
export type { PluginCancellationRegistration, PluginCancellationRequest } from '@wabs/plugin-sdk/cancellations';
export type { PluginJobEvent, PluginMessageEvent, PluginRuntimeHooks } from '@wabs/plugin-sdk/hooks';
export type { DurableFlowEngine as FlowEngine } from '@wabs/plugin-sdk/durable-flow';
export type { FlowSessionSnapshot } from '@wabs/plugin-sdk/flow-engine';
